### PR TITLE
Updates AMI and affected screenshot. Ref #133, #114

### PR DESCRIPTION
**Pull request by kerchner**
This PR updates the AMI to `ami-04dd77cd58b3ec654` (Ref #133, #114) and updates the affected setup instructions screenshot as well.  However, content in:
- https://datacarpentry.org/cloud-genomics/ (PR is https://github.com/datacarpentry/cloud-genomics/pull/116)
- https://datacarpentry.github.io/wrangling-genomics/ (possibly no changes here -- TBD)
- https://datacarpentry.org/genomics-r-intro/

will ALL also need to be updated in order to precisely match the commands and outputs that learners will user/see when they are using the new AMI with its updated tools.

**_Therefore_**... I advise that this PR _not_ be merged until it can be merged (approximately) simultaneously with the 3 PRs that I will be creating on each of the referenced lesson repositories, so that we can avoid a time window where they are out of sync.

### CODE REVIEW

**Comment by naupaka** [comment]
Thanks @kerchner!!

@ErinBecker would it be possible for maintainers to get access to an instance with this new AMI to quickly run through the lessons to make sure they aren't causing issues? Who would be the right point person for getting those set up?

**Comment by ErinBecker** [comment]
@tobyhodges - could you please set up instances with the new AMI for Maintainers to test things out? Thank you!

**Comment by tobyhodges** [comment]
@datacarpentry/genomics-r-intro-maintainers you should find connection details for a test instance in your inbox. Please let me know if you need more than one.

**Comment by naupaka** [comment]
@tobyhodges thanks! I'll aim to work through the lessons this week.

**Comment by naupaka** [comment]
I put this in the email thread but adding it here as well so it's logged. I went through the entire set of Genomics lessons start to finish, including all the standard lessons and the R lessons, using the new AMI. There were no major issues with anything, except for the example Excel file in the R lesson -- the example files and the directory it is supposed to be in are not in the AMI. My recommendation for this is to just have the file hosted in the repo on GH and have students use curl/wget to pull it down during the workshop. This is something the R maintainers can fix in the lessons; it's more flexible this way if we want to change the contents of that file, and if we move forward that way it also means that I think the AMI is good to go as is! 🎉

I found a number of other issues/bugs as I went through, but none of them were AMI-related, so I will post those as issues on the various lesson repos (I'm sure some are already open issues).

**Comment by tobyhodges** [comment]
Huge thanks to @kerchner for preparing this updated AMI, and of course to @naupaka for testing it out. I will merge this now and update the FigShare entry to include the example Excel file for the R lesson.

**Comment by kerchner** [comment]
Thank you @naupaka @tobyhodges !  Looking forward to the merge of https://github.com/datacarpentry/cloud-genomics/pull/116 so that everything matches up.

**Pull request merged**
