### PR TITLE
Create touch

### PR DESCRIPTION
**Pull request by karinaeg**
Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

### CODE REVIEW

**Comment by twrightsman** [comment]
Hi @karinaeg! Thanks for the contribution. Could you clarify what exactly this PR is supposed to fix/improve?

**Comment by JCSzamosi** [comment]
It appears that an empty file called `touch` has been created in the `_includes` directory. Is it possible this was done by mistake, or just as a test of the pull request process?

**Comment by twrightsman** [comment]
I think both are possible; though it may also be possible that `_includes` is assumed to exist by some platforms when building the repository? I would need to look further into this before closing, unless the original contributor clarifies things before that.

**Comment by twrightsman** [comment]
Hi @karinaeg, I'm going to close this because all current PRs will soon be invalid due to the upcoming workbench transition and I haven't heard back. Please feel free to open another PR with more details on this change if this is a mistake!

**Pull request closed without merging**
